### PR TITLE
ENH add LICENSE

### LINKED ISSUE #25: Please specify and include license
Hi,

I'd like to package esutil for Fedora, therefore I need information on the licensing of the package. Can you specify the license and add a copy to the source tree? Thanks :)

Greetings,
Christian

### PR DESCRIPTION
**Pull request by beckermr**
I have added GPLv2.

Closes #25

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon for viz

**Comment by beckermr** [comment]
@esheldon you’ll want to include the license in the manifest as well so it gets pushed to pypi

**Comment by esheldon** [comment]
Do I just do this?
```
include LICENSE
```

**Comment by beckermr** [comment]
Yep. A commit with that is in this pr if you want it.

**Comment by esheldon** [comment]
sorry, got confused between issues and PRs.  I ended up pushing this to master

**Comment by beckermr** [comment]
No worries! Whatever works best for you!

**Pull request closed without merging**
