### PR TITLE
new version of match, match_multi using searchsorted.  Much faster.

### PR DESCRIPTION
**Pull request by erykoff**

### CODE REVIEW

**Comment by esheldon** [comment]
how much faster?

**Comment by erykoff** [comment]
Depends on the problem but ~10x isn't unreasonable for general uses. 

-Eli.

**Comment by esheldon** [comment]
do you know what this conflict is?

**Comment by erykoff** [comment]
No. The problem is that I forked a long time ago and only now am doing a pr. 

Maybe I should refork and start over?

-Eli.

**Comment by esheldon** [comment]
might be better just to see what is conflicting; probably something trivial

**Comment by esheldon** [comment]
also, we should probably make a unit test(s) for this to make sure it works the same

**Comment by esheldon** [comment]
lets get this working, matching is currently a bottleneck in my work!

**Pull request closed without merging**
