### PR TITLE
Use the properly formatted array to check first element.

### PR DESCRIPTION
**Pull request by erykoff**

### CODE REVIEW

**Review by esheldon — APPROVED** [review]

**Comment by esheldon** [comment]
Thanks

**Comment by esheldon** [comment]
Can you add a note in `RELEASE_NOTES`?

**Comment by erykoff** [comment]
I just assumed this would be part of the next release number for the RELEASE_NOTES.

**Comment by esheldon** [comment]
Sorry, can you also add a test for the failure you saw?

**Pull request merged**
