### PR TITLE
REF switch to string for ordering

### LINKED ISSUE #37: warnings for newer numpy versions
Looks like numpy is being persnickety. 

```
/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/esutil/wcsutil.py:1201: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
    x = x.flatten(1)
```

### PR DESCRIPTION
**Pull request by beckermr**
This pr closes #37.

I tested it locally. `'F'` is the right value.

```
In [1]: x = np.arange(5)                                                                                                                                                                                

In [2]: ones = np.ones(5)                                                                                                                                                                               

In [3]: np.outer(x, ones)                                                                                                                                                                               
Out[3]: 
array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [4]: np.outer(x, ones).flatten(1)                                                                                                                                                                    
/Users/Matt/miniconda3/envs/anl/bin/ipython:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  #!/Users/Matt/miniconda3/envs/anl/bin/python
Out[4]: 
array([0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 0., 1.,
       2., 3., 4., 0., 1., 2., 3., 4.])

In [5]: np.outer(x, ones).flatten('C')                                                                                                                                                                  
Out[5]: 
array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3.,
       3., 3., 3., 4., 4., 4., 4., 4.])

In [6]: np.outer(x, ones).flatten('F')                                                                                                                                                                  
Out[6]: 
array([0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 0., 1.,
       2., 3., 4., 0., 1., 2., 3., 4.])
```

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon for viz

**Comment by esheldon** [comment]
man, this deprecation of numbers must go back at least 10 years, I can't even find any info on it.

**Comment by beckermr** [comment]
Yeah none of the docs mention it.

**Comment by esheldon** [comment]
I also can't remember why I chose fortran ordering

**Comment by beckermr** [comment]
I don’t know either. The code produces the same results so the pr can be merged as is. 

I checked the numpy C and 1 is indeed FORTRAN ordering.

**Pull request merged**
